import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform

configurations { sqliteRaw }
configurations.maybeCreate("Sqlite Slim")

def os = DefaultNativePlatform.currentOperatingSystem
def arch = DefaultNativePlatform.currentArchitecture

def keepPath = [
        (['windows', 'x86_64']) : 'Windows/x86_64',
        (['windows', 'aarch64']): 'Windows/aarch64',
        (['linux', 'x86_64'])   : 'Linux/x86_64',
        (['linux', 'aarch64'])  : 'Linux/aarch64',
        (['macosx', 'x86_64'])  : 'Mac/x86_64',
        (['macosx', 'aarch64']) : 'Mac/aarch64',
].get([os.name.replace(' ', '').toLowerCase(), arch.name.replace('-', '_')])

if (!keepPath) {
    throw new GradleException("Unsupported platform: ${os.name}-${arch.name}")
}

def slimJarFile = file("${layout.buildDirectory.getAsFile().get()}/sqlite-jdbc-slim/sqlite-jdbc-3.50.3.0-${keepPath.replace('/', '-').toLowerCase()}.jar")

tasks.register('slimSqlite', Jar) {
    group = 'build'
    description = 'Build platform-stripped sqlite-jdbc jar'

    onlyIf { !slimJarFile.exists() }
    archiveFile.set(slimJarFile)

    def rawJar = configurations.sqliteRaw.resolve().find { it.name.contains('sqlite-jdbc') }

    from(zipTree(rawJar)) {
        exclude 'org/sqlite/native/**'
    }
    from(zipTree(rawJar)) {
        include "org/sqlite/native/${keepPath}/**"
    }

    destinationDirectory = slimJarFile.parentFile
    archiveVersion = ''
    archiveClassifier = ''
}

dependencies {
    sqliteRaw 'org.xerial:sqlite-jdbc:3.50.3.0'
    implementation files(slimJarFile).builtBy(slimSqlite)
}
