ext {
    // https://mvnrepository.com/artifact/org.apache.poi/poi
    poiVersion = "5.2.3"
}

dependencies {
    implementation project(':common')

    implementation libs.slf4j.simple
    implementation libs.common.excel

    runtimeOnly 'mysql:mysql-connector-java:8.0.29'
    runtimeOnly 'org.postgresql:postgresql:42.6.0'
    runtimeOnly 'org.xerial:sqlite-jdbc:3.50.3.0'
}

jar {
    manifest {
        attributes "Main-Class": "org.dreamcat.daily.script.Main"
    }
}
