ext {
    // https://mvnrepository.com/artifact/org.apache.poi/poi
    poiVersion = "5.2.3"
}

dependencies {
    implementation project(':common')

    implementation libs.slf4j.simple
    implementation libs.common.excel
}

jar {
    manifest {
        attributes "Main-Class": "org.dreamcat.daily.script.Main"
    }
}
